### ISSUE TITLE
Smaller pool by default 

### ISSUE THREAD

**Issue by rauchg** [vercel/fetch#14]
Right now it's 200, which is good for many use cases, but overkill for others. As an example, if you write a little utility that abstracts over `fetch`, and someone uses it as a module, they get a 200 socket pool by default.

A more reasonable default would be 50

**Comment by Ethan-Arrowood** [comment]
Thank you for the report. We are archiving this project; you can read more details here: https://github.com/vercel/fetch/issues/83
