### ISSUE TITLE
Multipart requests

### ISSUE THREAD

**Issue by RPallas92** [vercel/fetch#33]
Looks like multipart requests (like POST with Image) are not working.
Multipart requests with FormData body are not supported by the library, I see only string and Buffer are.

Should we do something similar to Buffer for FormData here? https://github.com/zeit/fetch/blob/master/index.js#L50

**Comment by Ethan-Arrowood** [comment]
Thank you for the report. We are archiving this project; you can read more details here: https://github.com/vercel/fetch/issues/83
