### ISSUE TITLE
Discuss a reasonable default `timeout`

### ISSUE THREAD

**Issue by rauchg** [vercel/fetch#4]
I think the current one is too high (socket timeout I believe). I think maybe 5s would be a good timeout?

**Comment by Allanflo88** [comment]
I think 5 seconds is fine as well, but what about 3 seconds based on google statistics of user leaving websites that take longer to respond?

**Comment by Ethan-Arrowood** [comment]
Thank you for the report. We are archiving this project; you can read more details here: https://github.com/vercel/fetch/issues/83
