### ISSUE TITLE
Investigate why `jest` exits immediately, since a socket pool is created

### ISSUE THREAD

**Issue by rauchg** [vercel/fetch#7]
I don't know why `jest` is so fast at quitting if sockets should be remaining open with the introduction of `agentkeepalive`

**Comment by Qix-** [comment]
@styfle Looks like a mistake, https://github.com/vercel/fetch/commit/32d78b48401e9729a37f38dfb0af97d3f7384e38 is just a license update entirely unrelated to this issue.

**Comment by Ethan-Arrowood** [comment]
Thank you for the report. We are archiving this project; you can read more details here: https://github.com/vercel/fetch/issues/83
