### ISSUE TITLE
Add better explanation/code example of the automatic peerdep on node-fetch

### ISSUE THREAD

**Issue by Qix-** [vercel/fetch#8]
Right now it's not clear than you can just do `require('@zeit/fetch')()` and that `require('@zeit/fetch')(require('node-fetch'))` isn't necessary.

The readme should explain this a little better.

**Comment by Ethan-Arrowood** [comment]
Thank you for the report. We are archiving this project; you can read more details here: https://github.com/vercel/fetch/issues/83
